### ISSUE TITLE
[Suggestion]: More than one item dropped

### ISSUE THREAD

**Issue by HavocStudio2** [Mrbysco/ResourcePandas#3]
### General Info

- [X] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

When the panda sneezing is their a way to increase how may items drop?// instead of one per sneezing and also make the Spore Blossom make the panda's sneezing more like a boost in the time it takes for the panda to sneezing

**Comment by Mrbysco** [comment]
You can change the item by creating a datapack and adjusting the result item

**Comment by HavocStudio2** [comment]
How do I increase the drops cause the datapack only drops 1 item per sneeze
